/* table, that represents users. */

create table users(
                      id BIGINT primary key generated by default as identity,
                      username VARCHAR(33) not null unique,
                      password_hash VARCHAR(255) not null,
                      email VARCHAR(255) not null unique,
                      is_email_verified boolean not null default false,

                      contains_profile_picture BOOLEAN not null default false,
                      profile_picture_url TEXT,

                      country_code VARCHAR(3) not null,
    /* how many likes user has */
                      commends BIGINT not null default 0,
    /* how many messages had user left */
                      messages BIGINT not null default 0,

                      created_at TIMESTAMPTZ not null default current_timestamp,
                      updated_at TIMESTAMPTZ not null default current_timestamp
);

/* table, that represents roots. Root is the main topic. */
create table roots(
                      id BIGINT primary key generated by default as identity,

                      author_id BIGINT not null,
                      foreign key (author_id)
                          references users(id),


                      title VARCHAR(255) not null,
                      description TEXT not null,

                      activity_rating INTEGER default 0 not null,

                      created_at timestamptz not null default current_timestamp,
                      updated_at timestamptz not null default current_timestamp
);

/* table, that represents branches. Branches belong to roots. */
create table branches(
                         id BIGINT primary key generated by default as identity,
                         root_id BIGINT not null,
                         foreign key (root_id)
                             references roots(id),

                         author_id BIGINT not null,
                         foreign key (author_id)
                             references users(id),

                         title VARCHAR(255) not null unique,
                         description TEXT not null,

                         comments_count INTEGER default 0,
                         rating INTEGER default 0,

                         tags VARCHAR(255),

                         contains_photo BOOLEAN,
                         photo_url TEXT,
                         created_at timestamptz not null default current_timestamp,
                         updated_at timestamptz not null default current_timestamp
);

/* leaves are related to branches, similar to comments */
create table leaves(
                       id BIGINT primary key generated by default as identity,
                       branch_id BIGINT not null,
                       foreign key (branch_id)
                           references branches(id),

                       author_id BIGINT not null,
                       foreign key (author_id)
                           references users(id),

                       commentary TEXT not null,
                       rating INTEGER default 0 not null,

                       created_at timestamptz not null default current_timestamp,
                       updated_at timestamptz not null default current_timestamp
);

/* email verification */
create table verification_tokens(
                                    id BIGINT primary key generated by default as identity,

                                    user_id BIGINT not null unique,
                                    foreign key (user_id)
                                        references users(id)
                                        on delete cascade,

                                    token VARCHAR(255) not null unique,

                                    expires_at timestamptz not null,

                                    created_at timestamptz not null default current_timestamp
);