/* table, that represents users. */

create table users(
                      id BIGINT primary key generated by default as identity,
                      username VARCHAR(30) not null unique,
                      password_hash VARCHAR(50) not null,
                      token_hash VARCHAR(200) not null unique,
                      country_code VARCHAR(3) not null,
    /* how many likes user has */
                      commends BIGINT default 0,
    /* how many messages had user left */
                      messages BIGINT default 0,
                      created_at TIMESTAMPTZ not null default current_timestamp
);
/* table, that represents nodes.*/
create table nodes(
    id BIGINT primary key GENERATED by default as identity,
    title VARCHAR (30) not null,
    /* how active is the node, the more active will appear first*/
    activity_rating INTEGER default 0 not null
);
/*  table, that represents branches. Subnodes, more specific questions/topics */
create table branches(
    id BIGINT primary key generated by default as identity,
    node_id BIGINT,
    foreign key (node_id)
        references nodes(id),
    author_id BIGINT,
    foreign key (author_id)
        references users(id),
    title TEXT not null,
    description TEXT not null,
    comments_count INTEGER default 0,
    /* amount of likes */
    rating INTEGER default 0,
    /* unique tags like: #question, #news, etc.. */
    tags VARCHAR(30) not null,
    /* does branch has photo or not */
    contains_photo BOOLEAN default false,
    /* original photo's url */
    photo_original_url TEXT,
    /* url, where we store the photo */
    photo_stored_url TEXT,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp
);

create table leaves(
    id BIGINT primary key generated by default as identity,
    branch_id BIGINT,
    foreign key (branch_id)
        references branches(id),
    author_id BIGINT,
    foreign key (author_id)
        references users(id),
    /* user's reaction/opinion/etc... */
    commentary TEXT not null,
    rating INTEGER default 0 not null,
    created_at timestamptz default current_timestamp not null,
    updated_at timestamptz default current_timestamp not null
);