/* table, that represents users. */

create table users(
                      id BIGINT primary key generated by default as identity,
                      username VARCHAR(33) not null unique,
                      password_hash VARCHAR(255) not null,
                      email VARCHAR(255) not null unique,
                      is_email_verified boolean not null default false,

                      contains_profile_picture BOOLEAN not null default false,
                      profile_picture_url TEXT,

                      country_code VARCHAR(3) not null,
    /* how many likes user has */
                      commends BIGINT not null default 0,
    /* how many messages had user left */
                      messages BIGINT not null default 0,

                      created_at TIMESTAMPTZ not null default current_timestamp,
                      updated_at TIMESTAMPTZ not null default current_timestamp
);

/* table, that represents roots. Root is the main topic. */
create table roots(
                      id BIGINT primary key generated by default as identity,

                      author_id BIGINT not null,
                      foreign key (author_id)
                          references users(id),


                      title VARCHAR(255) not null unique,
                      description TEXT not null,

                      activity_rating INTEGER default 0 not null,

                      created_at timestamptz not null default current_timestamp,
                      updated_at timestamptz not null default current_timestamp
);

/* table, that represents branches. Branches belong to roots. */
create table branches(
                         id BIGINT primary key generated by default as identity,
                         root_id BIGINT not null,
                         foreign key (root_id)
                             references roots(id),

                         author_id BIGINT not null,
                         foreign key (author_id)
                             references users(id),

                         title VARCHAR(255) not null unique,
                         description TEXT not null,

                         comments_count INTEGER default 0,
                         rating INTEGER default 0,

                         tags VARCHAR(255),

                         contains_photo BOOLEAN,
                         photo_url TEXT,
                         created_at timestamptz not null default current_timestamp,
                         updated_at timestamptz not null default current_timestamp
);

/* leaves are related to branches, similar to comments */
create table leaves(
                       id BIGINT primary key generated by default as identity,
                       branch_id BIGINT not null,
                       foreign key (branch_id)
                           references branches(id),

                       author_id BIGINT not null,
                       foreign key (author_id)
                           references users(id),

                       commentary TEXT not null,
                       rating INTEGER default 0 not null,

                       constraint uq_leaves_branch_author_commentary
                           unique (branch_id, author_id, commentary),

                       created_at timestamptz not null default current_timestamp,
                       updated_at timestamptz not null default current_timestamp
);

/* email verification */
create table verification_tokens(
                                    id BIGINT primary key generated by default as identity,

                                    user_id BIGINT not null unique,
                                    foreign key (user_id)
                                        references users(id)
                                        on delete cascade,

                                    token VARCHAR(255) not null unique,

                                    expires_at timestamptz not null,

                                    created_at timestamptz not null default current_timestamp
);

/* RabbitMQ outbox pattern, message guarantee */
CREATE TABLE outbox_events (
                               id UUID PRIMARY KEY,
                               event_type VARCHAR(255) NOT NULL,
                               exchange_name VARCHAR(255) NOT NULL,
                               routing_key VARCHAR(255) NOT NULL,
                               payload TEXT NOT NULL,
                               status VARCHAR(50) NOT NULL,
                               attempts INTEGER NOT NULL DEFAULT 0,
                               last_error TEXT,
                               created_at TIMESTAMP NOT NULL,
                               processing_at TIMESTAMP,
                               sent_at TIMESTAMP
);

CREATE INDEX idx_outbox_events_status_created_at
    ON outbox_events (status, created_at);

/* Table, that represents who liked a leaf */
CREATE TABLE leaf_likes (
                            id UUID PRIMARY KEY,
                            leaf_id BIGINT NOT NULL,
                            user_id BIGINT NOT NULL,
                            created_at TIMESTAMP NOT NULL,

                            CONSTRAINT uq_leaf_likes_leaf_user UNIQUE (leaf_id, user_id),

                            CONSTRAINT fk_leaf_likes_leaf
                                FOREIGN KEY (leaf_id) REFERENCES leaves(id),

                            CONSTRAINT fk_leaf_likes_user
                                FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_leaf_likes_leaf_id
    ON leaf_likes (leaf_id);

CREATE INDEX idx_leaf_likes_user_id
    ON leaf_likes (user_id);

CREATE TABLE consumer_events (
                            id BIGINT generated by default as identity PRIMARY KEY,
                            event_id UUID not null,
                            consumer_name VARCHAR(255) not null,
                            status VARCHAR(50) not null,
                            attempts int not null default(0),
                            last_error text,
                            created_at timestamp not null default current_timestamp,
                            updated_at timestamp not null default current_timestamp,

                            CONSTRAINT uq_consumer_event
                                UNIQUE (event_id, consumer_name)
);

    create index idx_consumer_event_status
        on consumer_events(status);

    create index idx_consumer_events_event_id
        on consumer_events(event_id);